/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.modulos;

import controlador.modulos.ControlCompras;
import javax.swing.JFrame;
import modelo.RegistroProductos;
import modelo.RegistroProveedor;

/**
 *
 * @author francisco
 */
public class GUICompras extends javax.swing.JDialog {

    private ControlCompras controlCompras;

    /**
     * Creates new form GUICompras
     */
    public GUICompras(JFrame parent, boolean modal, RegistroProveedor registroProveedor, RegistroProductos registroProductos) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.controlCompras = new ControlCompras(this, panelCompras1, registroProveedor, registroProductos);
        this.panelCompras1.escuchar(controlCompras);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCompras1 = new vista.modulos.PanelCompras();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCompras1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelCompras1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vista.modulos.PanelCompras panelCompras1;
    // End of variables declaration//GEN-END:variables
}
