/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.modulos;

import controlador.modulos.ControlInventario;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author francisco
 */
public class PanelInventario extends javax.swing.JPanel {

    /**
     * Creates new form PanelInventario
     */
    public PanelInventario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel_Agotados = new javax.swing.JLabel();
        jScrollPane_Tabla = new javax.swing.JScrollPane();
        jTable_Productos = new javax.swing.JTable();
        jButton_Cerrar = new javax.swing.JButton();
        jComboBox_Filtro = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(218, 223, 254));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setText("Inventario");

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel4.setText("Filtrar por:");

        jLabel_Agotados.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N

        jTable_Productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane_Tabla.setViewportView(jTable_Productos);

        jButton_Cerrar.setBackground(new java.awt.Color(254, 254, 254));
        jButton_Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salir2.png"))); // NOI18N
        jButton_Cerrar.setText("Cerrar");

        jComboBox_Filtro.setBackground(new java.awt.Color(254, 254, 254));
        jComboBox_Filtro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todo", "Disponibles", "Agotados" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(755, Short.MAX_VALUE)
                        .addComponent(jButton_Cerrar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane_Tabla, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_Agotados)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBox_Filtro, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox_Filtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel_Agotados)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane_Tabla, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addGap(31, 31, 31)
                .addComponent(jButton_Cerrar)
                .addGap(77, 77, 77))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Cerrar;
    private javax.swing.JComboBox jComboBox_Filtro;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_Agotados;
    private javax.swing.JScrollPane jScrollPane_Tabla;
    private javax.swing.JTable jTable_Productos;
    // End of variables declaration//GEN-END:variables

    public static final String BTN_CERRAR = "Cerrar";

    public void escuchar(ControlInventario ci) {
        this.jButton_Cerrar.addActionListener(ci);
        this.jComboBox_Filtro.addItemListener(ci);
    }

    public String getJComboBox_Filtro() {
        return jComboBox_Filtro.getSelectedItem().toString();
    }

    public void setJLabel_Agotados(ResultSet rsTabla) {
        String mensaje = "<HTML><FONT COLOR=\"red\">Productos Agotados:</FONT><BR>";
        try {
            while (rsTabla.next()) {
                if (rsTabla.getInt("cantidad") < 2) {
                    mensaje += rsTabla.getString("idProducto") + ", ";
                }
            }
        } catch (SQLException ex) {
        }
        mensaje = mensaje.substring(0, mensaje.length() - 2);
        mensaje += "</HTML>";
        this.jLabel_Agotados.setText(mensaje);
    }

    public void setjTable_Productos(ResultSet rsTabla) {
        DefaultTableModel tabla = new DefaultTableModel(new String[]{"Cod. producto", "Nombre producto", "Cod. proveedor", "Nombre proveedor", "Cantidad", "Última compra"}, 0);
        try {
            ResultSetMetaData columnas = rsTabla.getMetaData();
            while (rsTabla.next()) {
                Object[] fila = new Object[columnas.getColumnCount()];
                for (int i = 0; i < columnas.getColumnCount(); i++) {
                    fila[i] = rsTabla.getObject(i + 1);
                }
                tabla.addRow(fila);
            }
        } catch (SQLException ex) {
        }
        this.jTable_Productos.setModel(tabla);
        this.jScrollPane_Tabla.setViewportView(this.jTable_Productos);
    }
}
